### ISSUE TITLE
SVG resize problem

### ISSUE THREAD

**Issue by segonzal** [niclabs/city-dashboard#3]
When the Javascript console is closed, the svg layers don't rescale.

The markers disappear like they were behind a ghost console.

**Comment by alangrafu** [comment]
Miren http://gionkunz.github.io/chartist-js/ para ver tema de resize

**Comment by segonzal** [comment]
Funciona muy bien para reescalar la ventana. Pero aun tiene problemas al reescalar un elemento con propiedad css 'resizable'.
